Connected: Připojen
Disconnected: Odpojen
ConnectedClients n: Počet klientů : #{show n}
Direction: Směr
Payload: Data
Time: Čas
Port: Kanál
Counter: Počítadlo
Network: Síť
Settings: Nastavění
MessageCount n: Počet správ: #{show n}
Activation: Aktivace
Uplink: Uplink
DownLink: DownLink
TimeFormat: Formát času
TFTime: Čas
TFDateTime: Datum a čas
Temperature t: Teplota: #{showFloat t}
Humidity h: Vlhkost: #{showFloat h}
Home: Domů
Docs: Dokumentace
About: O aplikaci
Device: Zařízení
Application: Aplikace
LastReadings: Poslední měření
Frequency f: Frekvence: #{showFloat f}
DataRate x: Kódovaní: #{T.unpack x}
RSSISNR rssi snr: RSSI: #{showFloat rssi}dBm SNR: #{showFloat snr}dB
Channel chan: Kanál: #{show $ round chan}

Gateways: Brány
NMnM i: Nové Město na Moravě #{show i}
BaseGWOutdoor: base48.cz outdoor gateway
BaseGWIndoor: base48.cz indoor gateway
UnknownGw: Nneznámá brána

Language: Jazyk
LangCzech: Česky
LangSlovak: Slovensky
LangEnglish: Anglicky

EnglishResources: Anglický zdroje
CzechResources: Český zdroje

HomeIntro: Technologický demo otevřený LoRaWAN IoT sítě. Aplikace získává data z LoRaWAN zařízení připojenýho do
HomeSensor: Zařízení periodicky odesílá binárně zabalený hodnoty aktualní teploty a vlhkosti z I2C senzoru SHT22.
HomeAPI: Správy sú ziskávány z TTN MQTT API a odesílány přes Websocket servr do tyhle aplikace.
TTN: sítě The Things Tracker network

AboutPowered: Aplikaci pohání
AboutPowered2: a skvělý
AboutMiso: framework Miso
AboutSensor: Firmware zařízení je taktéž napsanej v jazyku Haskell pomocí
AboutIvoryTower: framework-u Ivory Tower
AboutGateways: Brány postavil
AboutHosted: Aplikace běží na
AboutBy: Vyrobil
AboutInCoOp: v spoluprácí s
AboutSources: Zdrojový kód
AboutThisApp: (tato aplikace)
