Connected: Pripojený
Disconnected: Odpojený
ConnectedClients n: Počet klientov: #{show n}
Direction: Smer
Payload: Dáta
Time: Čas
Port: Kanál
Counter: Počítadlo
Network: Sieť
Settings: Nastavenia
MessageCount n: Počet správ: #{show n}
Activation: Aktivácia
Uplink: Uplink
DownLink: DownLink
TimeFormat: Formát času
TFTime: Čas
TFDateTime: Dátum a čas
Temperature t: Teplota: #{showFloat t}
Humidity h: Vlhkosť: #{showFloat h}
Home: Domov
Docs: Dokumentácia
About: O aplikácii
Device: Zariadenie
Application: Aplikácia
LastReadings: Posledné merania
Frequency f: Frekvencia: #{showFloat f}
DataRate x: Kódovanie: #{T.unpack x}
RSSISNR rssi snr: RSSI: #{showFloat rssi}dBm SNR: #{showFloat snr}dB
Channel chan: Kanál: #{show $ round chan}

Gateways: Brány
NMnM i: Nové Město na Moravě #{show i}
BaseGWOutdoor: base48.cz outdoor gateway
BaseGWIndoor: base48.cz indoor gateway
UnknownGw: Neznáma brána

Language: Jazyk
LangCzech: Český
LangSlovak: Slovenský
LangEnglish: Anglický

EnglishResources: Anglické zdroje
CzechResources: České zdroje

HomeIntro: Technologické demo otvorenej LoRaWAN IoT siete. Aplikácia získava dáta z LoRaWAN zariadenia pripojeného do
HomeSensor: Zariadenie periodicky odosiela binárne zabalené hodnoty aktuálnej teploty a vlhkosti z I2C senzoru SHT22.
HomeAPI: Správy sú získavané z TTN MQTT API a odosielané cez Websocket server do tejto aplikácie.
TTN: siete The Things Network

AboutPowered: Aplikáciu poháňa
AboutPowered2: a výborný
AboutMiso: framework Miso
AboutSensor: Firmware zariadenia je taktiež písaný v jazyku Haskell pomocou
AboutIvoryTower: frameworku Ivory Tower
AboutGateways: Brány postavil
AboutHosted: Aplikácia beží na
AboutBy: Vyrobil
AboutInCoOp: v spolupráci s
AboutSources: Zdrojové kódy
AboutThisApp: (táto aplikácia)
